

service: aws-serverless-nodejs-opentelemetry

frameworkVersion: '2'

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"



functions:
  hello:
    handler: src/handler.hello
    layers:
      - arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:layer:aws-otel-collector:1
    #   - arn:aws:lambda:#{AWS::Region}:297975325230:layer:opentelemetry-lambda-extension:8
    # environment:
    #   OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yaml


